### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by thomasdavis** [lorenzodalaqua/jsonresume-theme-autumn#1]
Just doing some maintenance work on JSON Resume.

I ran up your repo, the theme is one of the most beautiful things I have ever seen. (kinda wanna make it my default) 

Could you publish it to npm?

**Comment by lorenzodalaqua** [comment]
Hi, thanks a lot! I'm really glad you liked it! By the way, great work on JSON Resume.

The theme was still a work in progress, but after your compliment I feel like it's good enough then :smile: 

I'll publish it to NPM, I just wanted to fix some small issues first, and probably name it like the other themes with a cool single word name :laughing: 

One issue I am having is a little trouble with responsive styles when rendering to PDF, it will render as if the screen is very small, after looking at the source of resume-cli it seems there is a `pdfViewport` config I need to set up, looking that up right now.

And also I have left the font family as the default from the Tailwind CSS framework for now, which is the system sans-serif UI, I don't know which one you got when testing the theme, that could change. I was going to set a font, probably Ubuntu because that's what I get in my system and I liked it. If you liked it with the font from your system let me know and I can publish it as it is right now.

**Comment by lorenzodalaqua** [comment]
Hi Thomas, I ended up publishing this on npm as [jsonresume-theme-autumn](https://www.npmjs.com/package/jsonresume-theme-autumn) (ended up naming it after all), so anyone can use it. 

I was very happy to hear you considered making it your default, I wasn't thinking much of it, having you notice this was a nice surprise :smiley:

I fixed the issues I mentioned and the layout now should work fine as responsive HTML and when exporting to PDF. I also set the font as Ubuntu so it's the same independent of where it is run. And I enhanced a few styles too, there's a screenshot in the README now.

Let me know what you think and if you have any issues or suggestions.

Cheers

**Comment by thomasdavis** [comment]
Woohoo!

https://registry.jsonresume.org/thomasdavis?theme=autumn

Works great, will add it to the official themes page and send out another tweet. 

And yeah the layout and PDF also is legit now.

**Comment by lorenzodalaqua** [comment]
Hey, I noticed I was using the wrong property for the company name (company instead of name), and fixed the margins on the reference section.

In the link you sent the company names are empty, that should be fixed now, published as v1.0.1.

If you see any more issues let me know, thanks!

**Comment by thomasdavis** [comment]
https://registry.jsonresume.org/thomasdavis?theme=autumn 

Updated! 

Adding to theme page now...

**Comment by lorenzodalaqua** [comment]
Okay, guess I'll close this issue then.

**Comment by thomasdavis** [comment]
Makes sense. I've added it now -> https://jsonresume.org/themes/

**Comment by lorenzodalaqua** [comment]
Looks great, thanks!
